name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2

      - name: Lint
        run: swift format lint --strict --recursive Sources Tests

  test-macos:
    name: Run macOS Tests (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: macos-15
          - os: macos-26
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

  test-linux:
    name: Run Linux Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Swift
        run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz
          tar zxf swiftly-$(uname -m).tar.gz
          ./swiftly init --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"
          hash -r

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
